#/opt/rh/rh-python38/root/usr/local/bin/ansible-playbook -i /opt/prod_code/network_config_backups/inventory/hosts /opt/prod_code/network_config_backups/playbooks/cisco_config_backup.yaml


---

- name: Network backup
  hosts: all
  gather_facts: false
  connection: network_cli

  vars:
    git_branch: /opt/Backups/f5/
    f5Provider:
      server: "{{ ansible_host }}"
      server_port: 443
      user: xxx
      password: xxx
      validate_certs: no
      transport: rest

  tasks:

    - name: "Create UCS archive"
      block:
        - name: "6.0: Backup F5 devices From Inventory"
          bigip_command:
            commands:
              - save sys ucs {{ inventory_hostname }}
            provider: "{{f5Provider}}"
          delegate_to: localhost

        - name: Fetch UCS archive
          bigip_ucs_fetch:
            src: "{{ inventory_hostname }}.ucs"
            dest: "/opt/Backups/F5/{{ inventory_hostname }}.ucs"
            provider: "{{f5Provider}}"
          delegate_to: localhost
      when: inventory_hostname in groups["f5"]

- name: GIT SECTION
  hosts: localhost

  tasks:
    - name: print time
      command: date
      register: time
      changed_when: false
      delegate_to: localhost
      run_once: yes

    - name: git commands
      shell: |
        git add --all .
         git commit -m "updated on {{time.stdout}}"
        git push
      args:
        chdir: /opt/Backups/
      delegate_to: localhost
      run_once: yes
