---

- name: Network backup
  hosts: all
  gather_facts: false
  connection: network_cli

  vars:
    git_branch: /opt/Backups/
    f5Provider:
      server: "{{ ansible_host }}"
      server_port: 443
      user: "{{ f5User }}"
      password: "{{ f5Pwd }}"
      validate_certs: no
      transport: rest
  


  tasks:

    - name: 1.0 Git Switch to target branch
      command: git checkout "{{ git_branch }}"
      args:
        chdir: "{{ git_branch }}"
      changed_when: false
      run_once: yes

    - name: 1.1 Git Synchronize with remote branch
      command: git pull
      args:
        chdir: "{{ git_branch }}"
      changed_when: false
      run_once: yes

    - name: "IOS CONFIG"
      block:
        - name: "2.0: Backup Cisco IOS devices From Inventory"
          ios_command:
            commands: show run
          register: output_router

        - name: SAVE IOS CONFIG
          copy:
            content: "{{ output_router.stdout[0] }}"
            dest: "{{ git_branch }}{{ inventory_hostname }}.txt"
      when: inventory_hostname in groups["ios"]

    - name: "NXOS CONFIG"
      block:
        - name: "3.0: Backup Cisco NXOS devices From Inventory"
          ios_command:
            commands: show run
          register: output_router

        - name: SAVE IOS CONFIG
          copy:
            content: "{{ output_router.stdout[0] }}"
            dest: "{{ git_branch }}{{ inventory_hostname }}.txt"
        - name: replace    
          replace:
            path: "{{ git_branch }}{{ inventory_hostname }}.txt"
            regexp: '^!Time.*$'
      when: inventory_hostname in groups["nxos"]     

    - name: "ASA CONFIG"
      block:
        - name: "4.0: Backup Cisco ASA devices From Inventory"
          ios_command:
            commands: show run
          register: output_router

        - name: SAVE IOS CONFIG
          copy:
            content: "{{ output_router.stdout[0] }}"
            dest: "{{ git_branch }}{{ inventory_hostname }}.txt"
      when: inventory_hostname in groups["asa"]   

    - name: "WLC CONFIG"
      block:
        - name: "5.0: Backup Cisco WLC devices From Inventory"
          ios_command:
            commands: show run
          register: output_router

        - name: SAVE IOS CONFIG
          copy:
            content: "{{ output_router.stdout[0] }}"
            dest: "{{ git_branch }}{{ inventory_hostname }}.txt"
      when: inventory_hostname in groups["wlc"]  

    - name: "Create UCS archive"
      block:
        - name: "6.0: Backup F5 devices From Inventory"
          bigip_command:
            commands:
              - save sys ucs {{ inventory_hostname }}
            provider: "{{f5Provider}}"
          delegate_to: localhost

        - name: Fetch UCS archive
          bigip_ucs_fetch:
            src: "{{ inventory_hostname }}.ucs"
            dest: "/opt/Backups/F5/{{ inventory_hostname }}.ucs"
            provider: "{{f5Provider}}"
          delegate_to: localhost
      when: inventory_hostname in groups["f5"]
      

- name: GIT SECTION
  hosts: localhost

  tasks:
    - name: print time
      command: date
      register: time
      changed_when: false
      delegate_to: localhost
      run_once: yes

    - name: git commands
      shell: |
        git add .
        # git commit -m "IN-564"
         git commit -m "Device Backup on {{time.stdout}}"
        git push
      args:
        chdir: /opt/Backups/
      delegate_to: localhost
      run_once: yes
